name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} '
          export DB_USERNAME="${{ secrets.DB_USERNAME }}";
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}";
          export DB_NAME="${{ secrets.DB_NAME }}";
          
          export MAVEN_HOME=/opt/apache-maven-3.9.6
          export PATH=$PATH:$MAVEN_HOME/bin
          export JAVA_HOME=/opt/amazon-corretto-17.0.10.8.1-linux-x64
          export PATH=$PATH:$JAVA_HOME/bin
          pkill -f quarkus-run.jar
          sleep 5
          cd /home/ubuntu/backend
          ./mvnw package
          nohup java -jar target/quarkus-app/quarkus-run.jar > app.log 2>&1 &
          echo "Deployment completed."
          '
