name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SSHKEY_GITHUB }}" > ./github_ssh_key
          scp -i ~/.ssh/id_rsa ./github_ssh_key ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/.ssh/github_ssh_key
          rm -f ./github_ssh_key
          
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "
            chmod 600 /home/ubuntu/.ssh/github_ssh_key
            eval \$(ssh-agent -s)
            ssh-add /home/ubuntu/.ssh/github_ssh_key
            ssh-keyscan github.com >> /home/ubuntu/.ssh/known_hosts
          
            git config --global url.'git@github.com:'.insteadOf 'https://github.com/'

            export DB_USERNAME='${{ secrets.DB_USERNAME }}';
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}';
            export DB_NAME='${{ secrets.DB_NAME }}';
            bash -l -s" < deploy_script.sh