name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} '
          export DB_USERNAME="${{ secrets.DB_USERNAME }}";
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}";
          export DB_NAME="${{ secrets.DB_NAME }}";
          
          source /home/ubuntu/backend/deploy_script.sh'
          '
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} 'bash -s' < /tmp/deploy_script.sh
